### ISSUE TITLE
OG images not working

### ISSUE THREAD

**Issue by bennihtm** [palmiak/tailblog-astro#10]
I don't know why, but the OG images just return `[object%20Object]` for my site. Can you tell me what I'm doing wrong?

My site is here: https://bendaha.eu.org and the repository here: https://github.com/bennihtm/astro-blog

**Comment by palmiak** [comment]
Thank you. I will check this out. Maybe while fixing something I introduced
a bug.

śr., 11 paź 2023, 12:25 użytkownik Benjamin ***@***.***>
napisał:

**Comment by palmiak** [comment]
Hey

So, thanks for spotting this. It should be fixed right now.

If you don't want to start from scratch, just edit the `SeoHead.astro` component, line 9 to:
```
const image = postData?.data?.image ? postData.data.image.src : config.defaultOgImage;
```

Thanks for giving Pacamara a try. It's nice seeing it "in the wild" :)

**Comment by bennihtm** [comment]
Thank you! Pacamara is really nice! :)
